dist: bionic
language: minimal
sudo: false
# Default `language: rust` has problems on nightly with rustfmt support

# only cache cargo subcommand binaries and .so libs
# the build artifacts take a lot of space and are slower to
# cache than to actually rebuild anyway...
# We need to cache the whole .cargo directory to keep the
# .crates.toml file.
cache:
  directories:
    - /home/travis/install
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf "$HOME"/.cargo/registry
before_script:
  - |
    export PATH="$HOME/.cargo/bin:$PATH"
    TRAVIS_RUST_VERSION="${TRAVIS_RUST_VERSION:-nightly}"
    if [ "$TRAVIS_RUST_VERSION" = 'nightly' ]; then
       printf -v RUSTFMT_VERSION '%s%s' '-' "$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt)"
       printf -v CLIPPY_VERSION '%s%s' '-' "$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/clippy)"
       SMALLEST_COMPAT_RUST="$([[ "$RUSTFMT_VERSION" < "$CLIPPY_VERSION" ]] && echo "$RUSTFMT_VERSION" || echo "$CLIPPY_VERSION")"

       if command -v rustup 2>/dev/null; then
           rustup default "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
       else
           curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
       fi
    fi
    if command -v cargo >/dev/null; then
      export PATH="$HOME/.cargo/bin:$PATH"
      export XDG_RUNTIME_DIR="$PWD"'/socket'
      mkdir "$XDG_RUNTIME_DIR"
      cargo fetch
      rustup component add rustfmt
    fi
    if [ -n "$CLIPPY" ]; then
      rustup component add clippy --toolchain "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
    elif [ -n "$BUILD_FMT" ]; then
      rustup component add rustfmt --toolchain "${TRAVIS_RUST_VERSION}${SMALLEST_COMPAT_RUST}"
    fi
script:
  - |
    if [ -n "$BUILD_FMT" ]; then
      cargo fmt --all -- --check
      # rustfmt --check # With: `src/*.rs` xor `"$(find -name '*.rs' -not -path './target/*')"`
    elif [ -n "$CLIPPY" ]; then
      cargo clippy --all -- -D warnings
    elif [ -n "$CARGO_TEST" ]; then
      cargo test --all --features "$FEATURES"
    fi

matrix:
  include:
    - rust: stable
      env: BUILD_FMT=1
    - rust: stable
      env: CLIPPY=1
    - rust: stable
      env: CARGO_TEST=1
    - stage: notify-website
      env:
        secure: 'Eo+4t4e2yolw++jiLvbeQtBb4Kks91pQ2GxQoPEjribiWin5QcGiZSvaBNGzJ3xpUZO4BR64N9cQOaFiiDUnm1wk1BJKloz1AM4wvF93biVM1QqUutGq262b+80q9V3p/tcf9EAEbuOVvNhO4eUDMPqurNRPC70KRSBcMayEBfadCNi0XMRoMVAqMjsczVlk/Kf4VSeMxS24VITLbvTDPvNbOCSxSW37JyoAEkdds9zanSawgEOT+tiSmx/DktrtVECMEcSCwD4iP5X/G5CWxkMMzarNjgwjab4JmndgMO35yVLK6Ue6uscAwVZxXcdyj13c0T6kxHAzF+shYZ5udA1001hl8FCYmq8p5+majx03HdVn7b7qA173I5LLO/ov/4+NPG99drZkbIfARhebWEpNC8PSSQ0n7ybzajLfFMTxLHWETMLRHaH+YksPqy2DKGwa/I3yuM2X3jpAMXR86fp+EWe/JgNmpVQzcn6APEMCNQ1hoXwy4q4nHVtvHzgogjII2NtOMnoWFGiqhvyUPVboOYCU6wpw3KzPL11JXUTdOIVNte6Qets0cqjqBmSYgbzmz6+PQtVNJuwIk/aJCmc6zxnxL9sSkMI029Lx3VP+uf5OcQE8YbD5De3BtwIO1QF+bhLGMRkXl6P8Tklbiywz0BT5wB6s9WztSm6QHf8='
      script:
        - email_author="$(git log -1 --pretty=format:'%an <%ce>')"
        - author="${email_author% *}"; git config --global user.name "$author"
        - email="${email_author#*<}"; email="${email::-1}"; git config --global user.email "$email"
        - git clone https://SamuelMarks:$GH_TOKEN@github.com/Fantom-foundation/fantom-dev-web
          && cd fantom-dev-web
        - echo "  | [$TRAVIS_REPO_SLUG](https://github.com/$TRAVIS_REPO_SLUG) | [$TRAVIS_COMMIT_MESSAGE](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT) |" >> CHANGESLOG.md
        - git add CHANGESLOG.md
        - git commit -m "[CHANGESLOG.md] $TRAVIS_REPO_SLUG - $TRAVIS_COMMIT_MESSAGE" 
        - git push -u origin master
